import type { Metadata } from 'next';
import '..styles/globals.css';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { Navbar } from '@/components/navbar';
import { Sidebar } from '@/components/sidebar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};
const inter = Inter({ subsets: ['latin'], weight: ['400', '700'] });

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
        >
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className='flex flex-col'>
                        <Navbar />
                    <Sidebar>{children}</Sidebar>
                    </div>
                    
                </ThemeProvider>
            </body>
        </html>
    );
}
